// Tabla generada automáticamente: Family Group (número y nombre) → Workforce Category
// Completa los valores vacíos si es necesario
module.exports = [
  { num: 1, name: 'At Home Coffee K-Cup Pod Coffee', workforce: 'WHOLE BEAN' },
  { num: 2, name: 'At Home Coffee Miscellaneous Pod Coffee', workforce: 'WHOLE BEAN' },
  { num: 3, name: 'At Home Coffee Packaged Coffee', workforce: 'WHOLE BEAN' },
  { num: 4, name: 'At Home Coffee Verismo Pod Coffee', workforce: 'WHOLE BEAN' },
  { num: 5, name: 'At Home Coffee VIA Instant Coffee', workforce: 'WHOLE BEAN' },
  { num: 6, name: 'At Home Refresher VIA Instant Refresher', workforce: 'WHOLE BEAN' },
  { num: 7, name: 'At Home Tea Packaged Tea', workforce: 'RETAIL TEA' },
  { num: 8, name: 'Alcohol Beer', workforce: 'N/A' },
  { num: 9, name: 'Alcohol Liqueur', workforce: 'N/A' },
  { num: 10, name: 'Alcohol Liquor', workforce: 'N/A' },
  { num: 11, name: 'Alcohol Wine', workforce: 'N/A' },
  { num: 12, name: 'Cocktail Classic Cocktail', workforce: 'N/A' },
  { num: 13, name: 'Cocktail Cold Brew Cocktail', workforce: 'N/A' },
  { num: 14, name: 'Cocktail Espresso Cocktail', workforce: 'N/A' },
  { num: 15, name: 'Cocoa Hot Chocolate', workforce: 'OTHER BEVERAGES' },
  { num: 16, name: 'Coffee Brewed Coffee', workforce: 'BREWED COFFEE' },
  { num: 17, name: 'Coffee Cold Brew', workforce: 'BREWED COFFEE' },
  { num: 18, name: 'Coffee Iced Coffee', workforce: 'BREWED COFFEE' },
  { num: 19, name: 'Espresso Americano', workforce: 'ESPRESSO BEVERAGES' },
  { num: 20, name: 'Espresso Blended Espresso', workforce: 'ESPRESSO BEVERAGES' },
  { num: 21, name: 'Espresso Cappuccino', workforce: 'ESPRESSO BEVERAGES' },
  { num: 22, name: 'Espresso Cortado', workforce: 'ESPRESSO BEVERAGES' },
  { num: 23, name: 'Espresso Espresso Shot', workforce: 'ESPRESSO BEVERAGES' },
  { num: 24, name: 'Espresso Flat White', workforce: 'ESPRESSO BEVERAGES' },
  { num: 25, name: 'Espresso Iced Sweetened Espresso', workforce: 'ESPRESSO BEVERAGES' },
  { num: 26, name: 'Espresso Latte', workforce: 'ESPRESSO BEVERAGES' },
  { num: 27, name: 'Espresso Macchiato', workforce: 'ESPRESSO BEVERAGES' },
  { num: 28, name: 'Espresso Mocha', workforce: 'ESPRESSO BEVERAGES' },
  { num: 29, name: 'Frappuccino Blended Espresso', workforce: 'BLENDED BEVERAGES' },
  { num: 30, name: 'Frappuccino Coffee Frappuccino', workforce: 'BLENDED BEVERAGES' },
  { num: 31, name: 'Frappuccino Creme Frappuccino', workforce: 'BLENDED BEVERAGES' },
  { num: 32, name: 'Frappuccino Juice Frappuccino', workforce: 'BLENDED BEVERAGES' },
  { num: 33, name: 'Milk Beverage Crème', workforce: 'OTHER BEVERAGES' },
  { num: 34, name: 'Milk Beverage Ice Cream', workforce: 'OTHER BEVERAGES' },
  { num: 35, name: 'Milk Beverage Milk', workforce: 'OTHER BEVERAGES' },
  { num: 36, name: 'Milk Beverage Smoothie', workforce: 'OTHER BEVERAGES' },
  { num: 37, name: 'Ready-to-Drink Coffee', workforce: 'OTHER RETAIL' },
  { num: 38, name: 'Ready-to-Drink Dairy', workforce: 'OTHER RETAIL' },
  { num: 39, name: 'Ready-to-Drink Espresso', workforce: 'OTHER RETAIL' },
  { num: 40, name: 'Ready-to-Drink Frappuccino', workforce: 'OTHER RETAIL' },
  { num: 41, name: 'Ready-to-Drink Juice', workforce: 'OTHER RETAIL' },
  { num: 42, name: 'Ready-to-Drink Refreshers', workforce: 'OTHER RETAIL' },
  { num: 43, name: 'Ready-to-Drink Soda', workforce: 'OTHER RETAIL' },
  { num: 44, name: 'Ready-to-Drink Tea', workforce: 'OTHER RETAIL' },
  { num: 45, name: 'Ready-to-Drink Water', workforce: 'OTHER RETAIL' },
  { num: 46, name: 'Refreshment Handcrafted Soda', workforce: 'REFRESHERS' },
  { num: 47, name: 'Refreshment Juice', workforce: 'REFRESHERS' },
  { num: 48, name: 'Refreshment Refreshers', workforce: 'REFRESHERS' },
  { num: 49, name: 'Refreshment Water', workforce: 'REFRESHERS' },
  { num: 50, name: 'Tea Blended Tea', workforce: 'TEA' },
  { num: 51, name: 'Tea Iced Tea', workforce: 'TEA' },
  { num: 52, name: 'Tea Steeped Tea', workforce: 'TEA' },
  { num: 53, name: 'Tea Latte', workforce: 'TEA' },
  { num: 54, name: 'Bakery Bagel', workforce: 'FOOD' },
  { num: 55, name: 'Bakery Bar', workforce: 'FOOD' },
  { num: 56, name: 'Bakery Bread', workforce: 'FOOD' },
  { num: 57, name: 'Bakery Cake', workforce: 'FOOD' },
  { num: 58, name: 'Bakery Cake Pop', workforce: 'FOOD' },
  { num: 59, name: 'Bakery Choux Pastry', workforce: 'FOOD' },
  { num: 60, name: 'Bakery Cookie', workforce: 'FOOD' },
  { num: 61, name: 'Bakery Doughnut', workforce: 'FOOD' },
  { num: 62, name: 'Bakery Laminated Pastry', workforce: 'FOOD' },
  { num: 63, name: 'Bakery Muffin', workforce: 'FOOD' },
  { num: 64, name: 'Bakery Pie', workforce: 'FOOD' },
  { num: 65, name: 'Bakery Pretzel', workforce: 'FOOD' },
  { num: 66, name: 'Bakery Scone', workforce: 'FOOD' },
  { num: 67, name: 'Bakery Snack Pretzel', workforce: 'FOOD' },
  { num: 68, name: 'Bakery Tart', workforce: 'FOOD' },
  { num: 69, name: 'Breakfast Sandwich', workforce: 'FOOD' },
  { num: 70, name: 'Breakfast Cereal', workforce: 'FOOD' },
  { num: 71, name: 'Breakfast Egg', workforce: 'FOOD' },
  { num: 72, name: 'Breakfast Fresh Fruit', workforce: 'FOOD' },
  { num: 73, name: 'Breakfast Griddle', workforce: 'FOOD' },
  { num: 74, name: 'Breakfast Yogurt', workforce: 'FOOD' },
  { num: 75, name: 'Lunch Flatbread', workforce: 'FOOD' },
  { num: 76, name: 'Lunch Food Add-in', workforce: 'FOOD' },
  { num: 77, name: 'Lunch Bowl', workforce: 'FOOD' },
  { num: 78, name: 'Lunch Bundle', workforce: 'FOOD' },
  { num: 79, name: 'Lunch Pasta', workforce: 'FOOD' },
  { num: 80, name: 'Lunch Protein Box', workforce: 'FOOD' },
  { num: 81, name: 'Lunch Salad', workforce: 'FOOD' },
  { num: 82, name: 'Lunch Sandwich', workforce: 'FOOD' },
  { num: 83, name: 'Lunch Small Plate', workforce: 'FOOD' },
  { num: 84, name: 'Lunch Soup', workforce: 'FOOD' },
  { num: 85, name: 'Lunch Wrap', workforce: 'FOOD' },
  { num: 86, name: 'Snack Candy', workforce: 'PACKAGED FOOD' },
  { num: 87, name: 'Snack Cheese', workforce: 'PACKAGED FOOD' },
  { num: 88, name: 'Snack Chips', workforce: 'PACKAGED FOOD' },
  { num: 89, name: 'Snack Chocolate', workforce: 'PACKAGED FOOD' },
  { num: 90, name: 'Snack Dip', workforce: 'PACKAGED FOOD' },
  { num: 91, name: 'Snack Dried Fruit', workforce: 'PACKAGED FOOD' },
  { num: 92, name: 'Snack Gum', workforce: 'PACKAGED FOOD' },
  { num: 93, name: 'Snack Ice Cream', workforce: 'PACKAGED FOOD' },
  { num: 94, name: 'Snack Meat', workforce: 'PACKAGED FOOD' },
  { num: 95, name: 'Snack Mints', workforce: 'PACKAGED FOOD' },
  { num: 96, name: 'Snack Nut', workforce: 'PACKAGED FOOD' },
  { num: 97, name: 'Snack Olive', workforce: 'PACKAGED FOOD' },
  { num: 98, name: 'Snack Popcorn', workforce: 'PACKAGED FOOD' },
  { num: 99, name: 'Snack Pudding', workforce: 'PACKAGED FOOD' },
  { num: 100, name: 'Snack Small Plate', workforce: 'PACKAGED FOOD' },
  { num: 101, name: 'Snack Bar', workforce: 'PACKAGED FOOD' },
  { num: 102, name: 'Snack Mix', workforce: 'PACKAGED FOOD' },
  { num: 103, name: 'Snack Pretzel', workforce: 'PACKAGED FOOD' },
  { num: 104, name: 'Brewing Accessory', workforce: 'BREWING EQUIPMENT' },
  { num: 105, name: 'Brewing Coffee Brewing', workforce: 'BREWING EQUIPMENT' },
  { num: 106, name: 'Brewing Kettle', workforce: 'BREWING EQUIPMENT' },
  { num: 107, name: 'Brewing Single Serve Brewing', workforce: 'BREWING EQUIPMENT' },
  { num: 108, name: 'Brewing Tea Brewing', workforce: 'BREWING EQUIPMENT' },
  { num: 109, name: 'Gift Pack Merchandise Pairing', workforce: 'OTHER RETAIL' },
  { num: 110, name: 'Lifestyle Apparel', workforce: 'OTHER RETAIL' },
  { num: 111, name: 'Lifestyle Art', workforce: 'OTHER RETAIL' },
  { num: 112, name: 'Lifestyle Consumer Electronic', workforce: 'OTHER RETAIL' },
  { num: 113, name: 'Lifestyle Cup', workforce: 'OTHER RETAIL' },
  { num: 114, name: 'Lifestyle Event', workforce: 'OTHER RETAIL' },
  { num: 115, name: 'Lifestyle Homeware', workforce: 'OTHER RETAIL' },
  { num: 116, name: 'Lifestyle Novelty', workforce: 'OTHER RETAIL' },
  { num: 117, name: 'Lifestyle Personal Accessory', workforce: 'OTHER RETAIL' },
  { num: 118, name: 'Lifestyle Stationery', workforce: 'OTHER RETAIL' },
  { num: 119, name: 'Lifestyle Toy & Game', workforce: 'OTHER RETAIL' },
  { num: 120, name: 'Media Book', workforce: 'OTHER RETAIL' },
  { num: 121, name: 'Media Magazine', workforce: 'OTHER RETAIL' },
  { num: 122, name: 'Media Music', workforce: 'OTHER RETAIL' },
  { num: 123, name: 'Media Newspaper', workforce: 'OTHER RETAIL' },
  { num: 124, name: 'Serveware Bottle', workforce: 'SERVEWARE' },
  { num: 125, name: 'Serveware Cup', workforce: 'SERVEWARE' },
  { num: 126, name: 'Serveware Drinkware Accesory', workforce: 'SERVEWARE' },
  { num: 127, name: 'Serveware Drinkware Accessory', workforce: 'SERVEWARE' },
  { num: 128, name: 'Serveware Kitchen Serving', workforce: 'SERVEWARE' },
  { num: 129, name: 'Serveware Storage', workforce: 'SERVEWARE' },
  { num: 130, name: 'Serveware Tumbler', workforce: 'SERVEWARE' },
  { num: 131, name: 'Bread Option', workforce: 'MODIFIERS' },
  { num: 132, name: 'Coffee Option', workforce: 'MODIFIERS' },
  { num: 133, name: 'Confection Jelly Option', workforce: 'MODIFIERS' },
  { num: 134, name: 'Confection Sweet Add-On Option', workforce: 'MODIFIERS' },
  { num: 135, name: 'Confection Sweet Powder Option', workforce: 'MODIFIERS' },
  { num: 136, name: 'Confection Sweet Sauce Option', workforce: 'MODIFIERS' },
  { num: 137, name: 'Confection Sweet Topping Option', workforce: 'MODIFIERS' },
  { num: 138, name: 'Confection Sweetener Option', workforce: 'MODIFIERS' },
  { num: 139, name: 'Confection Syrup Option', workforce: 'MODIFIERS' },
  { num: 140, name: 'Dairy Cheese Option', workforce: 'MODIFIERS' },
  { num: 141, name: 'Dairy Cold Foam Option', workforce: 'MODIFIERS' },
  { num: 142, name: 'Dairy Spread Option', workforce: 'MODIFIERS' },
  { num: 143, name: 'Dairy Ice Cream Option', workforce: 'MODIFIERS' },
  { num: 144, name: 'Dairy Milk Option', workforce: 'MODIFIERS' },
  { num: 145, name: 'Dairy Whipped Cream Option', workforce: 'MODIFIERS' },
  { num: 146, name: 'Dairy Yogurt Option', workforce: 'MODIFIERS' },
  { num: 147, name: 'Egg Option', workforce: 'MODIFIERS' },
  { num: 148, name: 'Espresso Base Option', workforce: 'MODIFIERS' },
  { num: 149, name: 'Espresso Caffeine Option', workforce: 'MODIFIERS' },
  { num: 150, name: 'Espresso Shot Option', workforce: 'MODIFIERS' },
  { num: 151, name: 'Espresso Shot Preparation Option', workforce: 'MODIFIERS' },
  { num: 152, name: 'Espresso Frappuccino Roast Option', workforce: 'MODIFIERS' },
  { num: 153, name: 'Fruit (blank)', workforce: 'MODIFIERS' },
  { num: 154, name: 'Fruit Dried Fruit Option', workforce: 'MODIFIERS' },
  { num: 155, name: 'Fruit Fresh Fruit Option', workforce: 'MODIFIERS' },
  { num: 156, name: 'Fruit Spread Option', workforce: 'MODIFIERS' },
  { num: 157, name: 'Fruit Juice Option', workforce: 'MODIFIERS' },
  { num: 158, name: 'Fruit Puree Option', workforce: 'MODIFIERS' },
  { num: 159, name: 'Grain Cereal Option', workforce: 'MODIFIERS' },
  { num: 160, name: 'Grain Option', workforce: 'MODIFIERS' },
  { num: 161, name: 'Grain Noodle Option', workforce: 'MODIFIERS' },
  { num: 162, name: 'Legume Option', workforce: 'MODIFIERS' },
  { num: 163, name: 'Legume Spread Option', workforce: 'MODIFIERS' },
  { num: 164, name: 'Meat Chicken Option', workforce: 'MODIFIERS' },
  { num: 165, name: 'Meat Fish Option', workforce: 'MODIFIERS' },
  { num: 166, name: 'Meat Option', workforce: 'MODIFIERS' },
  { num: 167, name: 'Meat Pork Option', workforce: 'MODIFIERS' },
  { num: 168, name: 'Nut Option', workforce: 'MODIFIERS' },
  { num: 169, name: 'Nut Spread Option', workforce: 'MODIFIERS' },
  { num: 170, name: 'Nut Seed Option', workforce: 'MODIFIERS' },
  { num: 171, name: 'Preparation Brew Method Option', workforce: 'MODIFIERS' },
  { num: 172, name: 'Preparation Espresso Shot Preparation Option', workforce: 'MODIFIERS' },
  { num: 173, name: 'Preparation Method Option', workforce: 'MODIFIERS' },
  { num: 174, name: 'Preparation Serveware Option', workforce: 'MODIFIERS' },
  { num: 175, name: 'Preparation Serving Option', workforce: 'MODIFIERS' },
  { num: 176, name: 'Preparation Temperature Option', workforce: 'MODIFIERS' },
  { num: 177, name: 'Seasoning Condiment Sauce Option', workforce: 'MODIFIERS' },
  { num: 178, name: 'Seasoning Dressing Option', workforce: 'MODIFIERS' },
  { num: 179, name: 'Seasoning Herb Option', workforce: 'MODIFIERS' },
  { num: 180, name: 'Seasoning Spice Option', workforce: 'MODIFIERS' },
  { num: 181, name: 'Tea Iced Tea Option', workforce: 'MODIFIERS' },
  { num: 182, name: 'Tea Infusion Option', workforce: 'MODIFIERS' },
  { num: 183, name: 'Tea Concentrate Option', workforce: 'MODIFIERS' },
  { num: 184, name: 'Tea Powder Option', workforce: 'MODIFIERS' },
  { num: 185, name: 'Tea Sachet Option', workforce: 'MODIFIERS' },
  { num: 186, name: 'Vegetable Greens Option', workforce: 'MODIFIERS' },
  { num: 187, name: 'Vegetable Option', workforce: 'MODIFIERS' },
  { num: 188, name: 'Vegetable Soup Option', workforce: 'MODIFIERS' },
  { num: 189, name: 'Water Flavored Water Option', workforce: 'MODIFIERS' },
  { num: 190, name: 'Water Ice Option', workforce: 'MODIFIERS' },
  { num: 191, name: 'Water Option', workforce: 'MODIFIERS' },
];
