// Tabla de mapeo: family group (número y nombre) → nuevo major group (custom)
// Edita los valores de newMajor según tu lógica de negocio
module.exports = [
    { num: 101, name: 'Snack Bar', newMajor: 'Snack Bar' },
    { num: 133, name: 'Confection Sweet Add-On Option', newMajor: 'Confection Sweet Add-On Option' },
    { num: 134, name: 'Confection Sweet Powder Option', newMajor: 'Confection Sweet Powder Option' },
    { num: 135, name: 'Confection Sweet Sauce Option', newMajor: 'Confection Sweet Sauce Option' },
    { num: 136, name: 'Confection Sweet Topping Option', newMajor: 'Confection Sweet Topping Option' },
    { num: 137, name: 'Confection Sweetener Option', newMajor: 'Confection Sweetener Option' },
    { num: 138, name: 'Confection Syrup Option', newMajor: 'Confection Syrup Option' },
    { num: 140, name: 'Dairy Cold Foam Option', newMajor: 'Dairy Cold Foam Option' },
    { num: 141, name: 'Dairy Spread Option', newMajor: 'Dairy Spread Option' },
    { num: 143, name: 'Dairy Milk Option', newMajor: 'Dairy Milk Option' },
    { num: 144, name: 'Dairy Whipped Cream Option', newMajor: 'Dairy Whipped Cream Option' },
    { num: 149, name: 'Espresso Shot Option', newMajor: 'Espresso Shot Option' },
    { num: 15, name: 'Cocoa Hot Chocolate', newMajor: 'Cocoa Hot Chocolate' },
    { num: 151, name: 'Espresso Frappuccino Roast Option', newMajor: 'Espresso Frappuccino Roast Option' },
    { num: 16, name: 'Coffee Brewed Coffee', newMajor: 'Coffee Brewed Coffee' },
    { num: 168, name: 'Nut Spread Option', newMajor: 'Nut Spread Option' },
    { num: 17, name: 'Coffee Cold Brew', newMajor: 'Coffee Cold Brew' },
    { num: 172, name: 'Preparation Method Option', newMajor: 'Preparation Method Option' },
    { num: 173, name: 'Preparation Serveware Option', newMajor: 'Preparation Serveware Option' },
    { num: 174, name: 'Preparation Serving Option', newMajor: 'Preparation Serving Option' },
    { num: 175, name: 'Preparation Temperature Option', newMajor: 'Preparation Temperature Option' },
    { num: 181, name: 'Tea Infusion Option', newMajor: 'Tea Infusion Option' },
    { num: 182, name: 'Tea Concentrate Option', newMajor: 'Tea Concentrate Option' },
    { num: 183, name: 'Tea Powder Option', newMajor: 'Tea Powder Option' },
    { num: 184, name: 'Tea Sachet Option', newMajor: 'Tea Sachet Option' },
    { num: 189, name: 'Water Ice Option', newMajor: 'Water Ice Option' },
    { num: 19, name: 'Espresso Americano', newMajor: 'Espresso Americano' },
    { num: 190, name: 'Water Option', newMajor: 'Water Option' },
    { num: 20, name: 'Espresso Blended Espresso', newMajor: 'Espresso Blended Espresso' },
    { num: 205, name: 'Refreshment Component', newMajor: 'Refreshment Component' },
    { num: 207, name: 'Milk Base Option', newMajor: 'Milk Base Option' },
    { num: 209, name: 'Hot Foam Preparation Option', newMajor: 'Hot Foam Preparation Option' },
    { num: 21, name: 'Espresso Cappuccino', newMajor: 'Espresso Cappuccino' },
    { num: 210, name: 'Preparation Grind Option', newMajor: 'Preparation Grind Option' },
    { num: 23, name: 'Espresso Espresso Shot', newMajor: 'Espresso Espresso Shot' },
    { num: 24, name: 'Espresso Flat White', newMajor: 'Espresso Flat White' },
    { num: 26, name: 'Espresso Latte', newMajor: 'Espresso Latte' },
    { num: 27, name: 'Espresso Macchiato', newMajor: 'Espresso Macchiato' },
    { num: 28, name: 'Espresso Mocha', newMajor: 'Espresso Mocha' },
    { num: 3, name: 'At Home Coffee Packaged Coffee', newMajor: 'At Home Coffee Packaged Coffee' },
    { num: 30, name: 'Frappuccino Coffee Frappuccino', newMajor: 'Frappuccino Coffee Frappuccino' },
    { num: 31, name: 'Frappuccino Creme Frappuccino', newMajor: 'Frappuccino Creme Frappuccino' },
    { num: 35, name: 'Milk Beverage Milk', newMajor: 'Milk Beverage Milk' },
    { num: 40, name: 'Ready-to-Drink Frappuccino', newMajor: 'Ready-to-Drink Frappuccino' },
    { num: 41, name: 'Ready-to-Drink Juice', newMajor: 'Ready-to-Drink Juice' },
    { num: 45, name: 'Ready-to-Drink Water', newMajor: 'Ready-to-Drink Water' },
    { num: 48, name: 'Refreshment Refreshers', newMajor: 'Refreshment Refreshers' },
    { num: 51, name: 'Tea Iced Tea', newMajor: 'Tea Iced Tea' },
    { num: 52, name: 'Tea Steeped Tea', newMajor: 'Tea Steeped Tea' },
    { num: 53, name: 'Tea Latte', newMajor: 'Tea Latte' },
    { num: 54, name: 'Bakery Bagel', newMajor: 'Bakery Bagel' },
    { num: 55, name: 'Bakery Bar', newMajor: 'Bakery Bar' },
    { num: 56, name: 'Bakery Bread', newMajor: 'Bakery Bread' },
    { num: 57, name: 'Bakery Cake', newMajor: 'Bakery Cake' },
    { num: 58, name: 'Bakery Cake Pop', newMajor: 'Bakery Cake Pop' },
    { num: 60, name: 'Bakery Cookie', newMajor: 'Bakery Cookie' },
    { num: 62, name: 'Bakery Laminated Pastry', newMajor: 'Bakery Laminated Pastry' },
    { num: 69, name: 'Breakfast Sandwich', newMajor: 'Breakfast Sandwich' },
    { num: 7, name: 'At Home Tea Packaged Tea', newMajor: 'At Home Tea Packaged Tea' },
    { num: 70, name: 'Breakfast Cereal', newMajor: 'Breakfast Cereal' },
    { num: 71, name: 'Breakfast Egg', newMajor: 'Breakfast Egg' },
    { num: 74, name: 'Breakfast Yogurt', newMajor: 'Breakfast Yogurt' },
    { num: 80, name: 'Lunch Protein Box', newMajor: 'Lunch Protein Box' },
    { num: 82, name: 'Lunch Sandwich', newMajor: 'Lunch Sandwich' },
    { num: 88, name: 'Snack Chips', newMajor: 'Snack Chips' },
    { num: 90, name: 'Snack Dip', newMajor: 'Snack Dip' },
    { num: 98, name: 'Snack Popcorn', newMajor: 'Snack Popcorn' },
];
